version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
hooks:
  BeforeInstall:
    - location: scripts/stop-nginx.sh
      runas: root
  AfterInstall:
    - location: scripts/start-nginx.sh
      runas: root
  ApplicationStart:
    - location: scripts/reload-nginx.sh
      runas: root